In [1]:
import cv2
import layoutparser as lp

In [19]:
image = cv2.imread("./test1.png")
image = image[..., ::-1] 

In [4]:
model = lp.models.Detectron2LayoutModel('lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config', 
                                 extra_config=["MODEL.ROI_HEADS.SCORE_THRESH_TEST", 0.8],
                                 label_map={0: "Text", 1: "Title", 2: "List", 3:"Table", 4:"Figure"})

config.yml?dl=1: 8.19kB [00:01, 4.14kB/s]
model_final.pth?dl=1: 330MB [02:28, 2.22MB/s]                               


In [20]:
layout=model.detect(image)

In [7]:
import warnings
warnings.filterwarnings("ignore") 


In [21]:
layout=model.detect(image)

In [23]:
layout

Layout(_blocks=[TextBlock(block=Rectangle(x_1=246.0516357421875, y_1=45.710880279541016, x_2=596.51904296875, y_2=253.23768615722656), text=None, id=None, type=Figure, parent=None, next=None, score=0.9850865602493286), TextBlock(block=Rectangle(x_1=41.831336975097656, y_1=45.48809051513672, x_2=519.620361328125, y_2=253.3079376220703), text=None, id=None, type=Figure, parent=None, next=None, score=0.984777569770813)], page_data={})

In [24]:
x_1=0
y_1=0
x_2=0
y_2=0

for l in layout:
  print(l)
  if l.type == 'Figure':
    x_1 = int(l.block.x_1)
    print(l.block.x_1)
    y_1 = int(l.block.y_1)
    x_2 = int(l.block.x_2)
    y_2 = int(l.block.y_2)
    
    break

TextBlock(block=Rectangle(x_1=246.0516357421875, y_1=45.710880279541016, x_2=596.51904296875, y_2=253.23768615722656), text=None, id=None, type=Figure, parent=None, next=None, score=0.9850865602493286)
246.0516357421875


In [25]:
print(x_1,y_1,x_2,y_2)

246 45 596 253


In [26]:
im = cv2.imread('./test1.png')

In [27]:
cv2.imwrite('test_im.png', im[y_1:y_2,x_1:x_2])

True

In [28]:
from paddleocr import PaddleOCR, draw_ocr

In [30]:
ocr = PaddleOCR(lang='en')
image_path = './test_im.png'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)[0]

download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar to /Users/vhmt.vn/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer/en_PP-OCRv3_det_infer.tar



  0%|          | 0.00/4.00M [00:00<?, ?iB/s]
  0%|          | 3.07k/4.00M [00:01<30:56, 2.16kiB/s]
  0%|          | 19.5k/4.00M [00:02<05:42, 11.6kiB/s]
  1%|          | 35.8k/4.00M [00:02<03:05, 21.4kiB/s]
  1%|▏         | 52.2k/4.00M [00:02<02:10, 30.3kiB/s]
  2%|▏         | 68.6k/4.00M [00:03<02:07, 30.7kiB/s]
  2%|▏         | 85.0k/4.00M [00:03<01:44, 37.5kiB/s]
  3%|▎         | 101k/4.00M [00:03<01:28, 43.9kiB/s] 
  3%|▎         | 118k/4.00M [00:03<01:19, 48.7kiB/s]
  3%|▎         | 134k/4.00M [00:04<01:13, 52.7kiB/s]
  4%|▍         | 151k/4.00M [00:04<01:09, 55.6kiB/s]
  4%|▍         | 167k/4.00M [00:04<01:06, 57.9kiB/s]
  5%|▍         | 183k/4.00M [00:04<01:04, 59.4kiB/s]
  5%|▍         | 200k/4.00M [00:05<01:02, 60.9kiB/s]
  5%|▌         | 216k/4.00M [00:05<01:19, 47.7kiB/s]
  6%|▌         | 249k/4.00M [00:05<00:56, 67.0kiB/s]
  7%|▋         | 265k/4.00M [00:06<00:56, 66.3kiB/s]
  7%|▋         | 298k/4.00M [00:06<00:44, 82.5kiB/s]
  8%|▊         | 314k/4.00M [00:06<00:47, 77.9

download https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar to /Users/vhmt.vn/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer/en_PP-OCRv3_rec_infer.tar



  0%|          | 0.00/9.96M [00:00<?, ?iB/s]
  0%|          | 3.07k/9.96M [00:00<27:03, 6.13kiB/s]
  0%|          | 19.5k/9.96M [00:00<05:28, 30.3kiB/s]
  0%|          | 35.8k/9.96M [00:01<07:31, 22.0kiB/s]
  1%|          | 52.2k/9.96M [00:09<41:03, 4.02kiB/s]
  1%|          | 68.6k/9.96M [00:10<26:06, 6.32kiB/s]
  1%|          | 85.0k/9.96M [00:10<17:39, 9.32kiB/s]
  1%|          | 118k/9.96M [00:10<09:22, 17.5kiB/s] 
  2%|▏         | 167k/9.96M [00:10<04:55, 33.2kiB/s]
  2%|▏         | 200k/9.96M [00:11<03:42, 44.0kiB/s]
  2%|▏         | 232k/9.96M [00:11<02:54, 55.8kiB/s]
  3%|▎         | 282k/9.96M [00:11<02:03, 78.4kiB/s]
  3%|▎         | 331k/9.96M [00:11<01:35, 100kiB/s] 
  4%|▍         | 396k/9.96M [00:12<01:11, 134kiB/s]
  4%|▍         | 445k/9.96M [00:12<01:04, 148kiB/s]
  5%|▍         | 495k/9.96M [00:12<00:59, 159kiB/s]
  6%|▌         | 560k/9.96M [00:12<00:50, 185kiB/s]
  6%|▌         | 609k/9.96M [00:13<00:49, 187kiB/s]
  7%|▋         | 675k/9.96M [00:13<00:44, 209kiB/s]

download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to /Users/vhmt.vn/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar



  0%|          | 0.00/2.19M [00:00<?, ?iB/s]
  0%|          | 3.07k/2.19M [00:00<03:45, 9.69kiB/s]
  1%|          | 19.5k/2.19M [00:00<00:43, 50.2kiB/s]
  2%|▏         | 35.8k/2.19M [00:00<00:36, 58.9kiB/s]
  4%|▍         | 85.0k/2.19M [00:00<00:18, 115kiB/s] 
  5%|▍         | 101k/2.19M [00:01<00:22, 91.7kiB/s]
  6%|▌         | 134k/2.19M [00:01<00:19, 105kiB/s] 
  8%|▊         | 167k/2.19M [00:01<00:17, 113kiB/s]
 16%|█▌        | 347k/2.19M [00:02<00:06, 297kiB/s]
 19%|█▉        | 413k/2.19M [00:02<00:06, 289kiB/s]
 24%|██▍       | 527k/2.19M [00:02<00:04, 341kiB/s]
 39%|███▉      | 855k/2.19M [00:02<00:02, 641kiB/s]
 42%|████▏     | 921k/2.19M [00:03<00:02, 517kiB/s]
 47%|████▋     | 1.04M/2.19M [00:03<00:02, 509kiB/s]
 50%|████▉     | 1.09M/2.19M [00:04<00:05, 212kiB/s]
 51%|█████▏    | 1.13M/2.19M [00:04<00:06, 169kiB/s]
 53%|█████▎    | 1.15M/2.19M [00:05<00:09, 113kiB/s]
 54%|█████▎    | 1.18M/2.19M [00:06<00:11, 90.8kiB/s]
 54%|█████▍    | 1.19M/2.19M [00:07<00:15, 64.2kiB/s]


[2023/10/19 11:40:35] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/Users/vhmt.vn/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/Users/vhmt.vn/.paddleocr/whl/rec/en/en_PP-OCRv3_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dic


I1019 11:40:35.926743 1591471744 analysis_config.cc:424] use_dlnne_:0
I1019 11:40:35.926829 1591471744 analysis_config.cc:424] use_dlnne_:0
I1019 11:40:35.926849 1591471744 analysis_config.cc:424] use_dlnne_:0
I1019 11:40:35.926865 1591471744 analysis_config.cc:424] use_dlnne_:0
---    Fused 0 subgraphs into layer_norm op.


[2023/10/19 11:40:36] ppocr WARNING: Since the angle classifier is not initialized, the angle classifier will not be uesd during the forward process
[2023/10/19 11:40:36] ppocr DEBUG: dt_boxes num : 18, elapse : 0.07433319091796875


---    Fused 0 subgraphs into layer_norm op.


[2023/10/19 11:40:38] ppocr DEBUG: rec_res num  : 18, elapse : 1.6089918613433838


In [31]:
print(output)

[[[[50.0, 8.0], [76.0, 11.0], [74.0, 29.0], [48.0, 25.0]], ('city', 0.8954572677612305)], [[[148.0, 12.0], [191.0, 12.0], [191.0, 27.0], [148.0, 27.0]], ('Region', 0.9966583251953125)], [[[252.0, 13.0], [313.0, 13.0], [313.0, 25.0], [252.0, 25.0]], ('Profession', 0.9961961507797241)], [[[10.0, 47.0], [55.0, 47.0], [55.0, 62.0], [10.0, 62.0]], ('Denver', 0.9973166584968567)], [[[125.0, 47.0], [210.0, 47.0], [210.0, 61.0], [125.0, 61.0]], ('Intermountain', 0.9913104772567749)], [[[226.0, 47.0], [289.0, 47.0], [289.0, 62.0], [226.0, 62.0]], ('Spiderman', 0.9975297451019287)], [[[9.0, 80.0], [110.0, 81.0], [110.0, 96.0], [9.0, 95.0]], ('Sherwood Forest', 0.9785197973251343)], [[[125.0, 82.0], [180.0, 82.0], [180.0, 94.0], [125.0, 94.0]], ('European', 0.9969998598098755)], [[[225.0, 81.0], [266.0, 81.0], [266.0, 96.0], [225.0, 96.0]], ('Archer', 0.9980616569519043)], [[[10.0, 116.0], [61.0, 116.0], [61.0, 131.0], [10.0, 131.0]], ('La Barre', 0.9275311827659607)], [[[125.0, 116.0], [182.0, 1

In [32]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [33]:
image_boxes = image_cv.copy()

In [34]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [35]:
cv2.imwrite('detections.png', image_boxes)

True

In [36]:
im = image_cv.copy()


In [37]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)

In [38]:
cv2.imwrite('horiz_vert.png',im)

True

In [39]:
import tensorflow as tf

2023-10-19 11:49:38.298039: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [40]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [43]:
import numpy as np

In [44]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 1  5  8 11 13 17]


In [45]:
im_nms = image_cv.copy()

In [46]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)

In [47]:
cv2.imwrite('im_nms.png',im_nms)

True

In [48]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [49]:
print(vert_out)

tf.Tensor([8 3 7 0], shape=(4,), dtype=int32)


In [50]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[0 3 7 8]


In [51]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)

In [52]:
cv2.imwrite('im_nms.png',im_nms)

True

In [53]:
out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(6, 4)
[['', '', '', ''], ['', '', '', ''], ['', '', '', ''], ['', '', '', ''], ['', '', '', ''], ['', '', '', '']]


In [54]:
unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[50, 0, 74, 208]
[10, 0, 55, 208]
[125, 0, 180, 208]
[225, 0, 266, 208]


In [55]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[1 0 2 3]


In [56]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [57]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0
      
  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))
  
  return inter / float(box_1_area + box_2_area - inter)

In [58]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [59]:
out_array=np.array(out_array)

In [60]:
out_array

array([['', 'city', 'Region', 'Profession'],
       ['Denver', '', 'Intermountain', 'Spiderman'],
       ['Sherwood Forest', 'Sherwood Forest', 'European', 'Archer'],
       ['La Barre', 'La Barre', 'European', 'Starship Captain'],
       ['Nixa', '', 'Central', 'CIA Agent'],
       ['Smallville', 'Smallville', 'Central', 'Superman']], dtype='<U16')

In [61]:
pd.DataFrame(out_array).to_csv('sample.csv')

NameError: name 'pd' is not defined

In [62]:
import pandas as pd

In [63]:
pd.DataFrame(out_array).to_csv('sample.csv')

In [64]:
current_bank=['']*len(out_array[0,:])
print(current_bank)

['', '', '', '']


In [65]:
def empty(arr):
  for i in arr:
    if i=='':
      return True
  return False

In [66]:
cleaned_array=[]

In [67]:
for i in range(len(out_array)):
  if not empty(out_array[i]):
    current_bank=[out_array[i][j] for j in range(len(out_array[i]))]
    cleaned_array.append(current_bank)
    not_empty=True
  else:
    for j in range(len(out_array[i])):
      current_bank[j]+=' '+out_array[i][j]
    print('-->',current_bank)
cleaned_array=np.array(cleaned_array)
print(cleaned_array)

--> [' ', ' city', ' Region', ' Profession']
--> ['  Denver', ' city ', ' Region Intermountain', ' Profession Spiderman']
--> ['La Barre Nixa', 'La Barre ', 'European Central', 'Starship Captain CIA Agent']
[['Sherwood Forest' 'Sherwood Forest' 'European' 'Archer']
 ['La Barre Nixa' 'La Barre ' 'European Central'
  'Starship Captain CIA Agent']
 ['Smallville' 'Smallville' 'Central' 'Superman']]


In [68]:
pd.DataFrame(cleaned_array).to_csv('cleaned.csv')